name:           klister
version:        0.1
github:         gelisam/klister
author:         David Christiansen <david@davidchristiansen.dk>,  Samuel Gélineau <gelisam@gmail.com>
maintainer:     David Christiansen <david@davidchristiansen.dk>,  Samuel Gélineau <gelisam@gmail.com>
tested-with:    GHC==8.6.5, GHC==8.8.1
ghc-options: -Wall
dependencies:
  - base
  - containers
  - directory
  - extra
  - filepath
  - lens
  - megaparsec
  - mtl
  - prettyprinter
  - text
library:
  source-dirs: src
executables:
  klister:
    main:        Main.hs
    source-dirs: repl
    dependencies:
      - optparse-applicative
      - klister
tests:
  klister-tests:
    main:
      tests/Test.hs
    dependencies:
      - call-stack
      - deepseq
      - hedgehog
      - klister
      - tasty
      - tasty-hunit
      - tasty-hedgehog
